Develop
ichika4561/Sports pull request #15
Opened 2019-02-10 04:56 UTC by ichika4561

### 概要

#7 
app/models/post.rbにて変更

### 動作確認方法

>Postモデルでデフォルト値とバリデーションを設定するのがいいと思います。
公式ドキュメントをみて書いてみましたが、エラーが起きてしまいます。
https://railsguides.jp/active_record_validations.html

お忙しいところ恐れ入りますが、アドバイス頂けると幸いです。

2019-02-10 05:00 UTC, abgata20000 commented
@ichika4561 コンフリクト起こしているので調整しましょう
[![Screenshot from Gyazo](https://gyazo.com/405e10c6c18ad955c92dae31baf8f275/raw)](https://gyazo.com/405e10c6c18ad955c92dae31baf8f275)

2019-02-10 05:29 UTC, abgata20000 requested changes
@ichika4561 無駄な改行やインデントのずれが入っているのが気になります
複数メンバーで開発するようになると余分な変更があった場合に競合したり等あっていろいろ面倒になることが多いので、IDEやエディタの自動整形やhttps://github.com/rubocop-hq/rubocop 等の導入をおすすめします

2019-02-10 05:29 UTC, abgata20000 commented on app/controllers/posts_controller.rb
> +
余分な改行?

2019-02-10 05:29 UTC, abgata20000 commented on app/controllers/application_controller.rb
> +
余分な改行?

2019-02-10 05:29 UTC, abgata20000 commented on app/models/post.rb
> +　validates :kind, presence: true
インデントズレてる

2019-02-10 06:00 UTC, abgata20000 commented on app/views/posts/new.html.slim
> +#ボタン部分_form.html.slimから呼び出し
slimはコメントいれるの`/`じゃなかったっけ？
`#`でコメントアウトになる？
`#`だとID指定になってしまうような気がします

2019-02-10 06:00 UTC, abgata20000 commented on db/migrate/20190205095707_create_posts.rb
> +      t.string :kind, null: false, comment:  "ジャンル:空白無"
ジャンルやエリアは選択肢の中から選ぶ等の実装になると思うので、
別モデルとして管理して紐付けるようにするほうがいい思います

2019-02-10 06:01 UTC, abgata20000 commented
@ichika4561 PRのタイトルは作業内容がわかるものにしましょう
[![Screenshot from Gyazo](https://gyazo.com/1f35fa9c90d51345072a1b9957508836/raw)](https://gyazo.com/1f35fa9c90d51345072a1b9957508836)

今回の場合だったら、「スキーマ設計の見直し」とか

2019-02-10 07:43 UTC, ichika4561 commented on app/controllers/posts_controller.rb
> +
了解しました！

2019-02-10 07:45 UTC, ichika4561 commented on app/controllers/posts_controller.rb
> +
>IDEやエディタの自動整形やhttps://github.com/rubocop-hq/rubocop
ご指摘ありがとうございます！
いじっている際に無駄な改行が入ってしまったようです。
気をつけます。

2019-02-10 07:49 UTC, ichika4561 commented on app/views/posts/new.html.slim
> +#ボタン部分_form.html.slimから呼び出し
>slimはコメントいれるの`/`じゃなかったっけ？
`/`でした。修正します。

2019-02-10 07:52 UTC, ichika4561 commented on db/migrate/20190205095707_create_posts.rb
> +      t.string :kind, null: false, comment:  "ジャンル:空白無"
>ジャンルやエリアは選択肢の中から選ぶ等の実装になると思う

確かにそうですね。。。
ご指摘ありがとうございますー！

>別モデルとして管理して紐付けるようにするほうがいい思います

その場合は同じマイグレーションファイルには入れない方が良いってことですよね。
修正します。

2019-02-11 00:08 UTC, abgata20000 commented
@ichika4561 [![Screenshot from Gyazo](https://gyazo.com/346386d50ada8ea9184ed00b708cb262/raw)](https://gyazo.com/346386d50ada8ea9184ed00b708cb262)

また b784aaf の変更だけだとジャンルとエリアが管理できなくなっているだけなので、
genre管理用のテーブルとarea管理用のテーブルを追加して
postsにgenre_idとarea_idを追加して管理できるようにしましょう。

masterとdevelopとの間でコンフリクト発生してしまっているのでそれも解消しましょう
※このままだとマージできません

2019-02-11 04:44 UTC, merged

2019-02-11 04:48 UTC, ichika4561 commented
お疲れ様ですー！
変更内容わかるようにと言うことで、承知しました。
プルリクのやり方調べたら、同じコミットメッセージを使う方が良いとのことでしたが、
気をつけます。
https://teratail.com/questions/122843


>genre管理用のテーブルとarea管理用のテーブルを追加して
>postsにgenre_idとarea_idを追加して管理できるようにしましょう。

genre管理用のテーブルとarea管理用のテーブル一緒にではなく、
別々にマイグレーションファイルを作成して管理した方が良いですよね？