READMEにコンセプトの記入
ichika4561/Sports pull request #4
Opened 2019-02-07 03:22 UTC by ichika4561

### 概要
お疲れ様です。

自分用に参考したサイトなどをまとめました。
必要機能はもっとあるんですが、取りいそぎ必要そうなものだけ
書き出しました。

何か有れば変更して頂ければと思います。

＜相談＞
投稿用のマイグレーションファイル
/db/migrate/20190205095707_create_posts
のカラムが名称と詳細しかないため、いくつか追加したいです。

方法１　（やりたい方法）
・20190205095707_create_posts
を直接書き換えて
db:migrate:resetで再度作り直す。

方法２、代替案
カラム追加用のマイグレーションファイルを新規作成

理由
まだ、データ入れてないため影響が少ない、管理面からマイグレーションファイルを増やしたくない

ご意見頂けると幸いです。
宜しくお願い致します。

2019-02-07 15:13 UTC, abgata20000 commented
@ichika4561 PRやissueを作成する際には担当者やラベルを設定するとわかりやすくなります
[![Screenshot from Gyazo](https://gyazo.com/8351fc0c92b4c4441118ad16a009e6aa/raw)](https://gyazo.com/8351fc0c92b4c4441118ad16a009e6aa)

また、stream等つくっていなくて、更新なかなか気づけないのでメンション付きでコメントもらえるとありがたいです

2019-02-07 15:17 UTC, abgata20000 requested changes
@ichika4561 Markdown記法が適切に使用されていないため、
レイアウトが崩れてしまっています
[![Screenshot from Gyazo](https://gyazo.com/e50c13580336fbd368bc9c00bdeeae73/raw)](https://gyazo.com/e50c13580336fbd368bc9c00bdeeae73)

↓とかを参考に書き直してみてください
- https://qiita.com/tbpgr/items/989c6badefff69377da7
- https://qiita.com/Qiita/items/c686397e4a0f4f11683d

2019-02-07 15:30 UTC, abgata20000 commented
@ichika4561 
>投稿用のマイグレーションファイル
/db/migrate/20190205095707_create_posts
のカラムが名称と詳細しかないため、いくつか追加したいです。
>方法１　（やりたい方法）
・20190205095707_create_posts
を直接書き換えて
db:migrate:resetで再度作り直す。
>方法２、代替案
カラム追加用のマイグレーションファイルを新規作成
>理由
まだ、データ入れてないため影響が少ない、管理面からマイグレーションファイルを増やしたくない
ご意見頂けると幸いです。
宜しくお願い致します。

前提としてmigrationファイルを書き換えるとなると他の環境(deployしているサーバーや他の作業者のローカル等)でもDBのリセットを行わないといけなくなるので、
基本的には一度masterやdevelop等の反映用のサーバーに紐付いているブランチにマージしたのであればmigrationファイルを書き換えるのはやめたほうがいいと思います。

自分の作業ブランチでの作業中で他の環境に影響がない場合であれば、方法1でもいいと思いますが、
それ移行は方法2で対応するのが基本になると思います。

特に本番環境が稼働したあとでDBにデータが登録されているような状態では気軽にリセットするのも難しくなると思います。

ただ、現状は本番稼働しているわけでもなく、他の開発メンバーもいないので特に困ることもないので、
方法1で作り直してしまってもいいとは思います。

こういったことは多々あると思いますので、スキーマ設計はしっかり行うようにしていきましょう

また、少し話が変わってしまいますが、スキーマの変更が多くなってmigrationファイル管理が大変と言うのであれば、
https://github.com/winebarrel/ridgepole
のようなGemもあったりするので要件によってはこういったものを利用するのもいいと思います。
※最初はmigrationで管理するのがいいと思います

2019-02-07 15:33 UTC, abgata20000 commented
@ichika4561 
あと現状だと、masterブランチへのプロテクトかかってなくてどんな状態でもPRがマージできてしまうのでプロテクトかけておいたほうがいいですよ

[![Screenshot from Gyazo](https://gyazo.com/59b726e4bf18f66f4414fd9966d8d583/raw)](https://gyazo.com/59b726e4bf18f66f4414fd9966d8d583)

2019-02-08 07:27 UTC, ichika4561 commented
大変分かりやすく、ご指摘頂きましてありがとうございます。
対応いたします！

2019-02-08 11:00 UTC, ichika4561 commented
READ.MEをマークダウン形式利用して書き直しました！
事前にRANSNACKのgem追加してて、そちらもも反映されてしまっていますが、
気になさらないで頂けると助かります！

```
自分の作業ブランチでの作業中で他の環境に影響がない場合であれば、方法�1でもいいと思いますが、
それ移行は方法2で対応するのが基本になると思います。
```

丁寧な詳細解説ありがとうございます
最初の設計が正直きちんと考えられていなかったので気をつけます！


```
また、少し話が変わってしまいますが、スキーマの変更が多くなってmigrationファイル管理が大変と言うのであれば、
https://github.com/winebarrel/ridgepole
のようなGemもあったりするので要件によってはこういったものを利用するのもいいと思います。
※最初はmigrationで管理するのがいいと思います
```
gem ridgepoleのご紹介ありがとうございます。

2019-02-08 12:23 UTC, abgata20000 approved these changes
LGTM

2019-02-08 12:26 UTC, merged